module CSDL
  module TargetValues

    COUNTRY_CODES_BY_COUNTRY = {
      "Austria" => "AT",
      "Bahrain" => "BH",
      "Belgium" => "BE",
      "Bulgaria" => "BG",
      "Croatia" => "HR",
      "Cyprus" => "CY",
      "Czech Republic" => "CZ",
      "Denmark" => "DK",
      "Egypt" => "EG",
      "Estonia" => "EE",
      "Finland" => "FI",
      "France" => "FR",
      "Germany" => "DE",
      "Ghana" => "GH",
      "Greece" => "GR",
      "Hungary" => "HU",
      "Iceland" => "IS",
      "Iraq" => "IQ",
      "Ireland" => "IE",
      "Israel" => "IL",
      "Italy" => "IT",
      "Jordan" => "JO",
      "Kenya" => "KE",
      "Kuwait" => "KW",
      "Latvia" => "LV",
      "Lebanon" => "LB",
      "Lithuania" => "LT",
      "Luxembourg" => "LU",
      "Macedonia, the former Yugoslav Republic of" => "MK",
      "Malta" => "MT",
      "Mauritius" => "MU",
      "Morocco" => "MA",
      "Netherlands" => "NL",
      "Nigeria" => "NG",
      "Norway" => "NO",
      "Oman" => "OM",
      "Palestinian territories" => "PS",
      "Poland" => "PL",
      "Portugal" => "PT",
      "Qatar" => "QA",
      "Romania" => "RO",
      "Saudi Arabia" => "SA",
      "Serbia" => "RS",
      "Slovakia" => "SK",
      "Slovenia" => "SI",
      "South Africa" => "ZA",
      "Spain" => "ES",
      "Sweden" => "SE",
      "Switzerland" => "CH",
      "Tunisia" => "TN",
      "Turkey" => "TR",
      "Ukraine" => "UA",
      "United Arab Emirates" => "AE",
      "United Kingdom" => "GB",
      "United States" => "US",
    }.freeze

    COUNTRIES = COUNTRY_CODES_BY_COUNTRY.keys.freeze

    COUNTRY_CODES = COUNTRY_CODES_BY_COUNTRY.values.freeze

  end
end
