module CSDL
  module TargetValues

    COUNTRY_CODES_BY_COUNTRY = {
      "Austria" => "AT",
      "Bahrain" => "BH",
      "Belgium" => "BE",
      "Bolivia" => "BO",
      "Brazil" => "BR",
      "Bulgaria" => "BG",
      "Canada" => "CA",
      "Chile" => "CL",
      "Colombia" => "CO",
      "Costa Rica" => "CR",
      "Croatia" => "HR",
      "Cuba" => "CU",
      "Cyprus" => "CY",
      "Czech Republic" => "CZ",
      "Denmark" => "DK",
      "Dominican Republic" => "DO",
      "Ecuador" => "EC",
      "Egypt" => "EG",
      "El Salvador" => "SV",
      "Estonia" => "EE",
      "Finland" => "FI",
      "France" => "FR",
      "French Guiana" => "GF",
      "Germany" => "DE",
      "Ghana" => "GH",
      "Greece" => "GR",
      "Guadeloupe" => "GP",
      "Guatemala" => "GT",
      "Haiti" => "HT",
      "Honduras" => "HN",
      "Hungary" => "HU",
      "Iceland" => "IS",
      "Iraq" => "IQ",
      "Ireland" => "IE",
      "Israel" => "IL",
      "Italy" => "IT",
      "Jordan" => "JO",
      "Kenya" => "KE",
      "Kuwait" => "KW",
      "Latvia" => "LV",
      "Lebanon" => "LB",
      "Lithuania" => "LT",
      "Luxembourg" => "LU",
      "Macedonia, the former Yugoslav Republic of" => "MK",
      "Malta" => "MT",
      "Martinique" => "MQ",
      "Mauritius" => "MU",
      "Mexico" => "MX",
      "Morocco" => "MA",
      "Netherlands" => "NL",
      "Nicaragua" => "NI",
      "Nigeria" => "NG",
      "Norway" => "NO",
      "Oman" => "OM",
      "Palestinian territories" => "PS",
      "Panama" => "PA",
      "Paraguay" => "PY",
      "Peru" => "PE",
      "Poland" => "PL",
      "Portugal" => "PT",
      "Puerto Rico" => "PR",
      "Qatar" => "QA",
      "Romania" => "RO",
      "Saint Barthelemy" => "BL",
      "Saint Martin (French Part)" => "MF",
      "Saudi Arabia" => "SA",
      "Serbia" => "RS",
      "Slovakia" => "SK",
      "Slovenia" => "SI",
      "South Africa" => "ZA",
      "Spain" => "ES",
      "Sweden" => "SE",
      "Switzerland" => "CH",
      "Tunisia" => "TN",
      "Turkey" => "TR",
      "Ukraine" => "UA",
      "United Arab Emirates" => "AE",
      "United Kingdom" => "GB",
      "United States" => "US",
      "Uruguay" => "UY",
      "Venezuela" => "VE",
    }.freeze

    COUNTRIES = COUNTRY_CODES_BY_COUNTRY.keys.freeze

    COUNTRY_CODES = COUNTRY_CODES_BY_COUNTRY.values.freeze

  end
end
