module CSDL
  module TargetValues

    TOPIC_CATEGORIES = [
      "Actor/Director",
      "Aerospace/Defense",
      "Airport",
      "Album",
      "Amateur Sports Team",
      "Anatomical Structure",
      "Animal Breed",
      "Animal",
      "App",
      "Appliances",
      "Art",
      "Artist",
      "Arts/Entertainment/Nightlife",
      "Arts/Humanities",
      "Athlete",
      "Attractions/Things to Do",
      "Author",
      "Automobiles and Parts",
      "Automotive",
      "Baby Goods/Kids Goods",
      "Bags/Luggage",
      "Bank/Financial Institution",
      "Bank/Financial Services",
      "Bar",
      "Biotechnology",
      "Blogger",
      "Board Game",
      "Book Genre",
      "Book Series",
      "Book Store",
      "Book",
      "Building Materials",
      "Business Person",
      "Business Services",
      "Business/Economy",
      "Camera/Photo",
      "Cars",
      "Cause",
      "Chef",
      "Chemicals",
      "Church/Religious Organization",
      "City",
      "Clothing",
      "Club",
      "Coach",
      "Color",
      "Comedian",
      "Commercial Equipment",
      "Community Organization",
      "Community",
      "Community/Government",
      "Company",
      "Competition",
      "Computers",
      "Computers/Internet",
      "Computers/Technology",
      "Concentration or Major",
      "Concert Tour",
      "Concert Venue",
      "Consulting/Business Services",
      "Country",
      "Course",
      "Cuisine",
      "Dancer",
      "Degree",
      "DESIGNER",
      "Disease",
      "Doctor",
      "Drink",
      "Drugs",
      "Editor",
      "Education",
      "Education/Work Status",
      "Electronics",
      "Elementary School",
      "Energy/Utility",
      "Engineering/Construction",
      "Entertainer",
      "Entertainment",
      "Entrepreneur",
      "Episode",
      "Event Planning/Event Services",
      "Event",
      "Farming/Agriculture",
      "Fictional Character",
      "Field of Study",
      "Food",
      "Food/Beverages",
      "Food/Grocery",
      "Furniture",
      "Games/Toys",
      "Geography_General",
      "Government Official",
      "Government Organization",
      "Government",
      "Health/Beauty",
      "Health/Medical/Pharmaceuticals",
      "Health/Medical/Pharmacy",
      "Health/Wellness",
      "High School Status",
      "Holiday",
      "Home Decor",
      "Home Improvement",
      "Home/Garden",
      "Hospital/Clinic",
      "Hotel",
      "Household Supplies",
      "Industrials",
      "Insurance Company",
      "Interest",
      "Internet/Software",
      "Island",
      "Jewelry/Watches",
      "Journalist",
      "Just For Fun",
      "Kitchen/Cooking",
      "Lake",
      "Landmark",
      "Language",
      "Lawyer",
      "Legal/Law",
      "Library",
      "Local Business",
      "Local/Travel",
      "Magazine",
      "Media/News/Publishing",
      "Medical Procedure",
      "Middle School",
      "Mining/Materials",
      "Monarch",
      "Mountain",
      "Movie character",
      "Movie Genre",
      "Movie Theater",
      "Movie",
      "Museum/Art Gallery",
      "Music Award",
      "Music Chart",
      "Music Video",
      "Music",
      "Musical Genre",
      "Musical Instrument",
      "Musician/Band",
      "Neighborhood",
      "News Personality",
      "News/Media",
      "Newspaper",
      "Non-Governmental Organization (NGO)",
      "Non-Profit Organization",
      "Null",
      "Office Supplies",
      "One-Time TV Program",
      "Organization",
      "Other",
      "Outdoor Gear/Sporting Goods",
      "Patio/Garden",
      "Performance Art",
      "Personal Blog",
      "Personal Website",
      "Pet Services",
      "Pet Supplies",
      "Pet",
      "Phone/Tablet",
      "Photographer",
      "Playlist",
      "Podcast",
      "Political Ideology",
      "Political Organization",
      "Political Party",
      "Politician",
      "Preschool",
      "Producer",
      "Product/Service",
      "Profession",
      "Professional Services",
      "Professional Sports Team",
      "Public Figure",
      "Public Places",
      "Publisher",
      "Radio Station",
      "Real Estate",
      "Record Label",
      "Recreation/Sports",
      "Reference",
      "Regional",
      "Religion",
      "Restaurant/Cafe",
      "Retail and Consumer Merchandise",
      "River",
      "School Sports Team",
      "School",
      "Science",
      "Shopping/Retail",
      "Small Business",
      "Society/Culture",
      "Software",
      "Song",
      "Spas/Beauty/Personal Care",
      "Sport",
      "Sports Event",
      "Sports League",
      "Sports Venue",
      "Sports/Recreation/Activities",
      "State/Province/Region",
      "Studio",
      "Teacher",
      "Teens/Kids",
      "Telecommunication",
      "Tools/Equipment",
      "Topic",
      "Tours/Sightseeing",
      "Transit Stop",
      "Transport/Freight",
      "Transportation",
      "Travel/Leisure",
      "TV Channel",
      "TV Genre",
      "TV Network",
      "TV Season",
      "TV Show",
      "TV",
      "TV/Movie Award",
      "University Status",
      "University",
      "Video Game",
      "Vitamins/Supplements",
      "Waterfall",
      "Website",
      "Wine/Spirits",
      "Work Position",
      "Work Project",
      "Work Status",
      "Writer",
      "Year"
    ].freeze

  end
end


